### PR TITLE
Change bytecode constants to uppercase

### PR DESCRIPTION
**Pull request by xliang6**
Signed-off-by: Xiaoli Liang <xliang6@gmail.com>

### CODE REVIEW

**Comment by xliang6** [comment]
@rwy0717 Please review and merge. Thanks.

**Review by youngar — CHANGES_REQUESTED** [review]
Even though we are not compiling it in the next branch, can you please update the jit.cpp to use the new constants?  See `bool MethodBuilder::generateILForBytecode`

**Comment by rwy7** [comment]
I would like to use underscores in the names, I think it's more conventional.

For example `intPushConstant` -> `INT_PUSH_CONSTANT` (not `INTPUSHCONSTANT`).

Does anyone else care?

EDIT: You know what, it's not hard to read as-is, so I'm okay with the names. Ignore me :)

**Comment by xliang6** [comment]
@youngar I will update jit.cpp with the new names.
@rwy0717 I am okay with having underscores in the names. 

I will make the changes and do another push. Thanks.

**Comment by youngar** [comment]
I like the underscores better as well, but I have a feeling we're going to change the bytecode names again at some point, so I'm not too worried.

**Comment by xliang6** [comment]
@youngar @rwy0717 I think I have addressed both of your concerns. Please review.

**Review by rwy7 — APPROVED** [review]
LGTM, thanks @xliang6.

**Review by youngar — APPROVED** [review]

**Pull request merged**
