### PR TITLE
Reorganize our code

### PR DESCRIPTION
**Pull request by rwy7**
- Move include to b9/
- Move external stuff to third_party (googletest, omr)
- Move all test programs to test/
- Rename b9docker to docker
- Misc cleanup

### CODE REVIEW

**Comment by rwy7** [comment]
@xliang6 @arianneb: Take a look at the directory layout [here](https://github.com/rwy0717/Base9/tree/next). Let me know if there is anything else we want to reorg.

**Review by xliang6 — CHANGES_REQUESTED** [review]
Please change b9/include/b9/{callstyle,core,hash,jit,loader,module}.hpp to b9/include/{callstyle,core,hash,jit,loader,module}.hpp.

**Comment by youngar** [comment]
We have the `b9` directory under `b9/include/b9` so that we can reference headers with `#include "b9/core.hpp"`.  If both the old layout and this new layout are not working for you, we could just put the header files alongside the source files.

**Review by xliang6 — APPROVED** [review]

**Comment by xliang6** [comment]
I think the new include layout is fine after a quick chat with Rob. Thanks.

**Comment by rwy7** [comment]
Rebased and fixed merge issue. Updated OMR to latest.

**Pull request merged**
