### PR TITLE
Clean up options and configuration

### PR DESCRIPTION
**Pull request by rwy7**
combine the JitConfig and VirtualMachineConfig into one class: Config.

Remove the CallStyle enum, and restore the old semantics of three
features. The operandstack option was renamed to lazyVmState.

Signed-off-by: Robert Young <rwy0717@gmail.com>

### CODE REVIEW

**Comment by rwy7** [comment]
Two things:
1. I renamed `RunConfig::vm` to `RunConfig::b9`, because it's now a unified b9 config. Is the name OK?
2. I introduced a `Config::feature`, a struct holding our feature flags. I thought `cfg.feature.lazyVmState` read cleaner than `cfg.lazyVmStateEnabled`, but maybe it's too fancy? It's easy to change.

Thoughts @youngar @xliang6  ?

**Comment by youngar** [comment]
1.  Looks good to me
2. Doesn't really matter to me.  It is a little fancy

Still need to get rid of `b9/callstyle.hpp`.  I'm still trying to think of a better name than `lazyVmStateEnabled`, maybe something with `virtualized` in the name?

**Comment by xliang6** [comment]
The new command-line options are a lot more understandable and cleaner. What you use underneath in Config doesn't matter to me either. Another option is to get rid of feature struct, and call the flags jit, directCall, passParam, and lazyVmState to mimic the command-line options?

**Comment by rwy7** [comment]
Got rid of the feature struct and deleted the callstyle enum. I left lazyVmState as-is.

**Comment by rwy7** [comment]
I'm hitting merge on this, since I'm writing code that uses the cfg.

**Pull request merged**
