### PR TITLE
Implement for loops in the frontend

### PR DESCRIPTION
**Pull request by rwy7**
There were some other issues with compiling JMP in the jit, and compiling update-assignment expressions in the JS FE, which I fixed. I also added two small for-loop tests.

### CODE REVIEW

**Comment by youngar** [comment]
Another broken call to `handle()`.
```c++
	// Iterate expressions array
	this.handleSequenceExpression = function (func, sequence) {
		var expressions = sequence.expressions;
		var droplast = !decl.isParameter;

		for (expression in sequence.expressions.slice(0, -1)) {
			this.handle(func, expression);
			func.instructions.push(new Instruction("DROP"));
		}

		var last = sequence.expressions.slice(-1)[0];
		this.handle(last);

		if (!sequence.isParameter) {
			func.instructions.push(new Instruction("DROP"));
		}
	};
```

**Comment by rwy7** [comment]
I'll open an issue for the second busted handle and deal with it later, cool?

**Comment by youngar** [comment]
@rwy0717  Sounds good, we can fix that later.  

Unrelated question: do we want the coveralls check failing if we reduce test coverage?

**Comment by rwy7** [comment]
I was thinking about the same thing. Really, it's up to us to decide how to interpret the results. The threshold is configurable. I thought it was a little silly that it complains about a 0.009 % reduction in coverage, so I upped the threshold to 1%. I also disabled the comment--which I'm open to reenabling.

**Pull request merged**
